version: 2.1
orbs:
  orb-tools: circleci/orb-tools@10.0
  coralogix: coralogix/coralogix@dev:alpha
commands:
  test-send:
    steps:
      - run: echo "Hello world!" > build.log
      - coralogix/send:
          file: build.log
          application: coralogix-orb
          subsystem: ci
          category: tests
  test-tag:
    steps:
      - coralogix/tag:
          tag: v1.0.0
          applications: coralogix-orb
          subsystems: ci
jobs:
  integration-tests:
    docker:
      - image: cimg/base:current
    steps:
      - run: apk update
      - run: apk upgrade
      - run: apk add --no-cache openssh
      - run: apk add git
      - checkout
      - test-send
      - test-tag
workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: coralogix/coralogix
          context: orb-publishing
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev
