version: 2.1
orbs:
  orb-tools: circleci/orb-tools@10.0
  coralogix: coralogix/coralogix@<<pipeline.parameters.dev-orb-version>>
parameters:
  run-integration-tests:
    description: An internal flag.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
    type: string
    default: "dev:alpha"
commands:
  test-send:
    steps:
      - run: echo "Hello world!" > build.log
      - coralogix/send:
          file: build.log
          application: coralogix-orb
          subsystem: ci
          category: tests
  test-tag:
    steps:
      - coralogix/tag:
          tag: v1.0.0
          applications: coralogix-orb
          subsystems: ci
jobs:
  integration-tests:
    docker:
      - image: cimg/base:current
    steps:
      - run: apk update
      - run: apk upgrade
      - run: apk add --no-cache openssh
      - run: apk add git
      - checkout
      - test-send
      - test-tag
workflows:
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: coralogix/coralogix
          context: orb-publishing
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev
  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: coralogix/coralogix
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          filters:
            branches:
              only:
                - master
                - main
