---
description: |
  Defines the command to help ship workflow logs to Coralogix.
parameters:
  circle_token:
    type: env_var_name
    description: |
      Your CircleCI personal access token for interacting with the API.
      You can generate one here: https://circleci.com/account/api
    default: CIRCLE_TOKEN
  keep_artifacts:
    type: boolean
    description: Keep generated workflow data.
    default: false
steps:
  - run:
      name: Build workflow data
      when: always
      command: <<include(scripts/tag.sh)>>
  - when:
      condition: <<parameters.keep_artifacts>>
      steps:
        - store_artifacts:
            path: /tmp/coralogix
